### ISSUE TITLE
Not showing up in Server List

### ISSUE THREAD

**Issue by segersniels** [Didstopia/colony-survival-server#10]
I have the server up and running and port forwarded 27016-17 on my router but am still unable to see the server in the server list. Is there anything else I'm missing?

```
version: '2'
services:
  colony:
    image: didstopia/colony-survival-server
    environment:
      SERVER_NAME: foo
      SERVER_PASSWORD: bar
    ports:
      - "27016:27016"
      - "27017:27017/tcp"
    volumes:
      - "...:/steamcmd/colonysurvival"
    restart: always
```

No errors in the logs.
